In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iris-dataset/iris.data


In [2]:
data = pd.read_csv("/kaggle/input/iris-dataset/iris.data")

In [3]:
data.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [4]:
data.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [5]:
df=data.rename(columns={"5.1": "Sepal Lengt(cm)","3.5":"Sepal Width(cm)","1.4":"Petal Length (cm)","0.2":"Petal Width(cm)","Iris-setosa":"Type"})

In [6]:
df.head()

Sepal Lengt(cm)  Sepal Width(cm)  Petal Length (cm)  Petal Width(cm)  \
0              4.9              3.0                1.4              0.2   
1              4.7              3.2                1.3              0.2   
2              4.6              3.1                1.5              0.2   
3              5.0              3.6                1.4              0.2   
4              5.4              3.9                1.7              0.4   

          Type  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [7]:
df.shape


(149, 5)

In [8]:
y= df.pop("Type")
X=df

In [9]:
print(X)
print(y)


     Sepal Lengt(cm)  Sepal Width(cm)  Petal Length (cm)  Petal Width(cm)
0                4.9              3.0                1.4              0.2
1                4.7              3.2                1.3              0.2
2                4.6              3.1                1.5              0.2
3                5.0              3.6                1.4              0.2
4                5.4              3.9                1.7              0.4
..               ...              ...                ...              ...
144              6.7              3.0                5.2              2.3
145              6.3              2.5                5.0              1.9
146              6.5              3.0                5.2              2.0
147              6.2              3.4                5.4              2.3
148              5.9              3.0                5.1              1.8

[149 rows x 4 columns]
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa


In [10]:
print(X.head())
print(y.head())

   Sepal Lengt(cm)  Sepal Width(cm)  Petal Length (cm)  Petal Width(cm)
0              4.9              3.0                1.4              0.2
1              4.7              3.2                1.3              0.2
2              4.6              3.1                1.5              0.2
3              5.0              3.6                1.4              0.2
4              5.4              3.9                1.7              0.4
0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Type, dtype: object


In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [12]:
model= LogisticRegression()

In [13]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [14]:
model.fit(X_train,y_train)

LogisticRegression()

In [15]:
y_pred=model.predict(X_test)

In [16]:
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)

[[15  0  0]
 [ 0  8  3]
 [ 0  1 11]]


In [17]:
accuracy=metrics.accuracy_score(y_test, y_pred)*100

In [18]:
print("Accuracy:",accuracy)

Accuracy: 89.47368421052632


In [19]:
new_input=[[3,4,5,4]] # predict function required 2D array input.
predictions = model.predict(new_input)
print(predictions)

['Iris-virginica']


/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"
